version: '3.7'
services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    command: pytest . -s
    volumes:
      - ./services/backend/:/usr/src/backend/
    expose:
      - 8080
    env_file:
      - ./.env
