version: '3.7'
services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    command: gunicorn start:create_app --bind 0.0.0.0:8080 --worker-class aiohttp.GunicornWebWorker
    volumes:
      - ./services/backend/:/usr/src/backend/
    expose:
      - 8080
    env_file:
      - ./.env
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/front'
      - '/usr/src/front/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/usr/src/backend/project/static
    ports:
      - 1228:80
    depends_on:
      - backend
  

volumes:
  static_volume: