version: '3.7'
services:
  web:
    build: ./services/web
    command: python start.py
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1234:1234
    env_file:
      - ./.env
  db:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user1234
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_DB=sampledb
  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/front'
      - '/usr/src/front/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  postgres_data:
